/**
 * Turret Priority — Move source code generator.
 *
 * Generates a custom turret_priority Move module from a TurretPriorityConfig.
 * The generated source is a self-contained Move package that can be published
 * via `sui client publish --build-env testnet`.
 *
 * Phase 1 approach: config is baked into module constants at compile time.
 * To change targeting rules, regenerate source, republish, and re-authorize.
 */

// ── Ship class constants ────────────────────────────────────────────────────

export const SHIP_CLASSES = {
	shuttle: { groupId: 31, label: "Shuttle" },
	corvette: { groupId: 237, label: "Corvette" },
	frigate: { groupId: 25, label: "Frigate" },
	destroyer: { groupId: 420, label: "Destroyer" },
	cruiser: { groupId: 26, label: "Cruiser" },
	combatBattlecruiser: { groupId: 419, label: "Combat Battlecruiser" },
} as const;

export const TURRET_TYPES = {
	autocannon: {
		typeId: 92402,
		label: "Autocannon (Mini Turret)",
		effective: ["shuttle", "corvette"],
	},
	plasma: { typeId: 92403, label: "Plasma (Turret)", effective: ["frigate", "destroyer"] },
	howitzer: {
		typeId: 92484,
		label: "Howitzer (Heavy Turret)",
		effective: ["cruiser", "combatBattlecruiser"],
	},
} as const;

// ── Config interface ────────────────────────────────────────────────────────

export interface TurretPriorityConfig {
	/** Module name for the published package (default: "turret_priority") */
	moduleName?: string;
	/** Base weight for unlisted targets (default: 30) */
	defaultWeight: number;
	/** Weight for KOS targets (default: 100) */
	kosWeight: number;
	/** Bonus weight when target is actively attacking (default: 40) */
	aggressorBonus: number;
	/** Bonus for a "friendly" who is attacking — traitor/spy gets maximum priority (default: 50) */
	betrayalBonus: number;
	/** Bonus weight when target HP is below threshold (default: 20) */
	lowHpBonus: number;
	/** HP threshold (0-100) for low HP bonus (default: 40) */
	lowHpThreshold: number;
	/** Bonus weight for effective ship class match (default: 25) */
	classBonus: number;
	/** Tribe IDs that should never be targeted (weight 0) — unless attacking */
	friendlyTribes: number[];
	/** Character IDs that should never be targeted (weight 0) — unless attacking */
	friendlyCharacters: number[];
	/** Tribe IDs to always prioritize (KOS weight) */
	kosTribes: number[];
	/** Character IDs to always prioritize (KOS weight) */
	kosCharacters: number[];
	/** Ship class group IDs this turret is effective against */
	effectiveClasses: number[];
}

export const DEFAULT_TURRET_PRIORITY_CONFIG: TurretPriorityConfig = {
	defaultWeight: 30,
	kosWeight: 100,
	aggressorBonus: 40,
	betrayalBonus: 50,
	lowHpBonus: 20,
	lowHpThreshold: 40,
	classBonus: 25,
	friendlyTribes: [],
	friendlyCharacters: [],
	kosTribes: [],
	kosCharacters: [],
	effectiveClasses: [],
};

// ── Source code generator ───────────────────────────────────────────────────

function padSlots<T>(arr: T[], size: number, fill: T): T[] {
	const result = arr.slice(0, size);
	while (result.length < size) result.push(fill);
	return result;
}

/**
 * Generate Move source code for a custom turret priority extension.
 * The returned string is the complete contents of `turret_priority.move`.
 */
export function generateTurretPrioritySource(config: TurretPriorityConfig): string {
	const mod = config.moduleName ?? "turret_priority";
	const friendlyTribes = padSlots(config.friendlyTribes, 8, 0);
	const friendlyChars = padSlots(config.friendlyCharacters, 8, 0);
	const kosTribes = padSlots(config.kosTribes, 4, 0);
	const kosChars = padSlots(config.kosCharacters, 4, 0);
	const effectiveClasses = padSlots(config.effectiveClasses, 2, 0);

	return `/// Auto-generated turret priority extension.
/// Generated by TehFrontier Periscope.
///
/// Priority logic:
///   Friendly tribes/characters (not attacking) → weight 0 (never shoot)
///   Friendly ATTACKING (betrayal) → weight ${config.kosWeight} + ${config.aggressorBonus} + ${config.betrayalBonus} = ${config.kosWeight + config.aggressorBonus + config.betrayalBonus} (highest priority)
///   KOS tribes/characters → weight ${config.kosWeight} (shoot first)
///   Aggressors → +${config.aggressorBonus} bonus
///   Low HP (<${config.lowHpThreshold}%) → +${config.lowHpBonus} bonus
///   Effective ship class → +${config.classBonus} bonus
///   Default → weight ${config.defaultWeight}
module ${mod}::${mod};

use sui::{bcs, event};
use world::{character::Character, turret::{Self, Turret, OnlineReceipt}};

#[error(code = 0)]
const EInvalidOnlineReceipt: vector<u8> = b"Invalid online receipt";

public struct TurretPriorityAuth has drop {}

public struct PriorityListUpdatedEvent has copy, drop {
    turret_id: ID,
    target_count: u64,
}

// ── Config constants ────────────────────────────────────────────────────
const DEFAULT_WEIGHT: u64 = ${config.defaultWeight};
const KOS_WEIGHT: u64 = ${config.kosWeight};
const AGGRESSOR_BONUS: u64 = ${config.aggressorBonus};
const BETRAYAL_BONUS: u64 = ${config.betrayalBonus};
const LOW_HP_BONUS: u64 = ${config.lowHpBonus};
const LOW_HP_THRESHOLD: u64 = ${config.lowHpThreshold};
const CLASS_BONUS: u64 = ${config.classBonus};

// ── Friendly tribes ─────────────────────────────────────────────────────
${friendlyTribes.map((v, i) => `const FRIENDLY_TRIBE_${i}: u32 = ${v};`).join("\n")}

// ── Friendly characters ─────────────────────────────────────────────────
${friendlyChars.map((v, i) => `const FRIENDLY_CHAR_${i}: u64 = ${v};`).join("\n")}

// ── KOS tribes ──────────────────────────────────────────────────────────
${kosTribes.map((v, i) => `const KOS_TRIBE_${i}: u32 = ${v};`).join("\n")}

// ── KOS characters ──────────────────────────────────────────────────────
${kosChars.map((v, i) => `const KOS_CHAR_${i}: u64 = ${v};`).join("\n")}

// ── Effective ship classes ──────────────────────────────────────────────
${effectiveClasses.map((v, i) => `const EFFECTIVE_CLASS_${i}: u64 = ${v};`).join("\n")}

// ── Entry point ─────────────────────────────────────────────────────────

public fun get_target_priority_list(
    turret: &Turret,
    _character: &Character,
    target_candidate_list: vector<u8>,
    receipt: OnlineReceipt,
): vector<u8> {
    assert!(receipt.turret_id() == object::id(turret), EInvalidOnlineReceipt);

    let candidates = turret::unpack_candidate_list(target_candidate_list);
    let mut return_list = vector::empty<turret::ReturnTargetPriorityList>();

    let mut i = 0;
    let len = candidates.length();
    while (i < len) {
        let candidate = &candidates[i];
        let char_tribe = candidate.character_tribe();
        let char_id = candidate.character_id();
        let group_id = candidate.group_id();

        let is_friendly = is_friendly_tribe(char_tribe) || is_friendly_character(char_id);

        if (is_friendly && !candidate.is_aggressor()) {
            // Friendly and not attacking — safe, weight 0
            return_list.push_back(turret::new_return_target_priority_list(
                candidate.item_id(),
                0,
            ));
            i = i + 1;
            continue
        };

        let mut weight = DEFAULT_WEIGHT;

        // Betrayal: friendly who IS attacking → max priority (spy/traitor)
        if (is_friendly && candidate.is_aggressor()) {
            weight = KOS_WEIGHT + AGGRESSOR_BONUS + BETRAYAL_BONUS;
            return_list.push_back(turret::new_return_target_priority_list(
                candidate.item_id(),
                weight,
            ));
            i = i + 1;
            continue
        };

        if (is_kos_tribe(char_tribe) || is_kos_character(char_id)) {
            weight = KOS_WEIGHT;
        };

        if (candidate.is_aggressor()) {
            weight = weight + AGGRESSOR_BONUS;
        };

        // hp_ratio() not available in world-contracts v0.0.18
        // if (candidate.hp_ratio() < LOW_HP_THRESHOLD && candidate.hp_ratio() > 0) {
        //     weight = weight + LOW_HP_BONUS;
        // };

        if (is_effective_class(group_id)) {
            weight = weight + CLASS_BONUS;
        };

        return_list.push_back(turret::new_return_target_priority_list(
            candidate.item_id(),
            weight,
        ));

        i = i + 1;
    };

    let result = bcs::to_bytes(&return_list);
    turret::destroy_online_receipt(receipt, TurretPriorityAuth {});

    event::emit(PriorityListUpdatedEvent {
        turret_id: object::id(turret),
        target_count: len,
    });

    result
}

// ── Lookup helpers ──────────────────────────────────────────────────────

fun is_friendly_tribe(tribe: u32): bool {
    if (tribe == 0) return false;
${friendlyTribes.map((_, i) => `    (FRIENDLY_TRIBE_${i} != 0 && tribe == FRIENDLY_TRIBE_${i})`).join(" ||\n")}
}

fun is_friendly_character(char_id: u64): bool {
    if (char_id == 0) return false;
${friendlyChars.map((_, i) => `    (FRIENDLY_CHAR_${i} != 0 && char_id == FRIENDLY_CHAR_${i})`).join(" ||\n")}
}

fun is_kos_tribe(tribe: u32): bool {
    if (tribe == 0) return false;
${kosTribes.map((_, i) => `    (KOS_TRIBE_${i} != 0 && tribe == KOS_TRIBE_${i})`).join(" ||\n")}
}

fun is_kos_character(char_id: u64): bool {
    if (char_id == 0) return false;
${kosChars.map((_, i) => `    (KOS_CHAR_${i} != 0 && char_id == KOS_CHAR_${i})`).join(" ||\n")}
}

fun is_effective_class(group_id: u64): bool {
    if (group_id == 0) return false;
${effectiveClasses.map((_, i) => `    (EFFECTIVE_CLASS_${i} != 0 && group_id == EFFECTIVE_CLASS_${i})`).join(" ||\n")}
}
`;
}

/**
 * Generate the Move.toml manifest for the turret priority package.
 */
export function generateTurretPriorityManifest(moduleName?: string): string {
	const name = moduleName ?? "turret_priority";
	return `[package]
name = "${name}"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[addresses]
${name} = "0x0"
`;
}
