[package]
name = "turret_shoot_all"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[addresses]
turret_shoot_all = "0x0"
