[package]
name = "gate_tribe"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[addresses]
gate_tribe = "0x0"
