[package]
name = "token_template"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.66.2" }
market = { local = "../market" }

[addresses]
token_template = "0x0"
