[package]
name = "ssu_market"
edition = "2024"
published-at = "0x40576ea9e07fa8516abc4820a24be12b0ad7678d181afba5710312d2a0ca6e48"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.66.2" }
world = { local = "../world_stillness" }
market = { local = "../market" }

[addresses]
ssu_market = "0x40576ea9e07fa8516abc4820a24be12b0ad7678d181afba5710312d2a0ca6e48"
