[package]
name = "ssu_unified"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }
market = { local = "../market" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
