/// Auto-generated turret priority extension.
/// Generated by TehFrontier Periscope.
///
/// Sentinel constants (1000001-1000009) are patched at publish time
/// with actual user-configured weights via bytecode template.
module turret_priority::turret_priority;

use sui::{bcs, event};
use world::{character::Character, turret::{Self, Turret, OnlineReceipt}};

#[error(code = 0)]
const EInvalidOnlineReceipt: vector<u8> = b"Invalid online receipt";

public struct TurretPriorityAuth has drop {}

public struct PriorityListUpdatedEvent has copy, drop {
    turret_id: ID,
    target_count: u64,
}

// ── Config constants (sentinels, patched at publish time) ────────────
const DEFAULT_WEIGHT: u64 = 30;
const KOS_WEIGHT: u64 = 100;
const AGGRESSOR_BONUS: u64 = 40;
const BETRAYAL_BONUS: u64 = 50;
const LOW_HP_BONUS: u64 = 20;
const LOW_HP_THRESHOLD: u64 = 40;
const CLASS_BONUS: u64 = 25;

// ── Effective ship classes (0 = disabled) ───────────────────────────────
const EFFECTIVE_CLASS_0: u64 = 0;
const EFFECTIVE_CLASS_1: u64 = 0;

// ── Entry point ─────────────────────────────────────────────────────────

public fun get_target_priority_list(
    turret: &Turret,
    _character: &Character,
    target_candidate_list: vector<u8>,
    receipt: OnlineReceipt,
): vector<u8> {
    assert!(receipt.turret_id() == object::id(turret), EInvalidOnlineReceipt);

    let candidates = turret::unpack_candidate_list(target_candidate_list);
    let mut return_list = vector::empty<turret::ReturnTargetPriorityList>();

    let mut i = 0;
    let len = candidates.length();
    while (i < len) {
        let candidate = &candidates[i];
        let char_tribe = candidate.character_tribe();
        let char_id = candidate.character_id();
        let group_id = candidate.group_id();

        let is_friendly = is_friendly_tribe(char_tribe) || is_friendly_character(char_id);

        if (is_friendly && !candidate.is_aggressor()) {
            return_list.push_back(turret::new_return_target_priority_list(
                candidate.item_id(),
                0,
            ));
            i = i + 1;
            continue
        };

        let mut weight = DEFAULT_WEIGHT;

        if (is_friendly && candidate.is_aggressor()) {
            weight = KOS_WEIGHT + AGGRESSOR_BONUS + BETRAYAL_BONUS;
            return_list.push_back(turret::new_return_target_priority_list(
                candidate.item_id(),
                weight,
            ));
            i = i + 1;
            continue
        };

        if (is_kos_tribe(char_tribe) || is_kos_character(char_id)) {
            weight = KOS_WEIGHT;
        };

        if (candidate.is_aggressor()) {
            weight = weight + AGGRESSOR_BONUS;
        };

        if (is_effective_class(group_id)) {
            weight = weight + CLASS_BONUS;
        };

        return_list.push_back(turret::new_return_target_priority_list(
            candidate.item_id(),
            weight,
        ));

        i = i + 1;
    };

    let result = bcs::to_bytes(&return_list);
    turret::destroy_online_receipt(receipt, TurretPriorityAuth {});

    event::emit(PriorityListUpdatedEvent {
        turret_id: object::id(turret),
        target_count: len,
    });

    result
}

// ── Lookup helpers (all empty -- weights-only mode) ──────────────────

fun is_friendly_tribe(_tribe: u32): bool {
    false
}

fun is_friendly_character(_char_id: u32): bool {
    false
}

fun is_kos_tribe(_tribe: u32): bool {
    false
}

fun is_kos_character(_char_id: u32): bool {
    false
}

fun is_effective_class(group_id: u64): bool {
    if (group_id == 0) return false;
    (EFFECTIVE_CLASS_0 != 0 && group_id == EFFECTIVE_CLASS_0) ||
    (EFFECTIVE_CLASS_1 != 0 && group_id == EFFECTIVE_CLASS_1)
}
