[package]
name = "gate_toll"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.18" }

[addresses]
gate_toll = "0x0"
